name: "jaguarportal-submit"
description: "Submit result analysis SBFL to Jaguar Portal and report on GitHub Action and Pull Request"
author: "ericksonlbs"

inputs:
  jaguarPortalProjectKey:
    description: "The key of the Jaguar Portal project"
    required: true
  jaguarPortalHostUrl:
    description: "The Jaguar Portal server URL"
    default: https://jaguarportalcloud.io
    required: true
  jaguarPortalClientId:
    description: "The Client Id from Jaguar Portal"
    required: true
  jaguarPortalClientSecret:
    description: "The Client Secret from Jaguar Portal"
    required: true
  jaguarPortalAnalysisPath:
    description: "The analysis path"
    required: true
    default: /target
  jaguarPortalSourcePath:
    description: "The source path"
    required: true
    default: /src/main/java
  jaguarPortalGitHubAccessToken:
    description: "GitHub Access Token to write comment in pull request"
    required: false    
    
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'check-square'
  color: 'blue'
